engines:
  tslint:
    enabled: true
    channel: beta
    checks:
      no-bitwise:
        enabled: false
      one-line:
        enabled: false
      semicolon:
        enabled: false
      typedef-whitespace:
        enabled: false
      no-shadowed-variable:
        enabled: false
ratings:
  paths:
    - "**.ts"
exclude_paths:
  - lib
  - test