plugins:
  tslint:
    enabled: true
    config: tslint.json
exclude_patterns:
  - "lib/"
  - "test/"
  - "examples/"
  - "src/**/v1/"
  - "src/**/v2/**/ContextualFileSystem.ts"
  - "src/**/v2/**/Resource.ts"