engines:
  tslint:
    enabled: true
    channel: beta
    checks:
      no-bitwise:
        enabled: false
      one-line:
        enabled: false
      semicolon:
        enabled: false
      typedef-whitespace:
        enabled: false
      no-shadowed-variable:
        enabled: false
      max-line-length:
        enabled: false
      forin:
        enabled: false
  grep:
    enabled: true
    config:
      patterns:
        optional-type-ungrouped:
          pattern: \?( )+:
          annotation: "Group '?' and ':' to get '<name> ?: <type>'"
          severity: minor
          categories: Compatibility
          path_patterns:
            - "**.ts"
        optional-type-not-separated:
          pattern: ([^ ]?:)|(?:[^ ])
          annotation: "Expected '<name> ?: <type>'"
          severity: minor
          categories: Compatibility
          path_patterns:
            - "**.ts"
ratings:
  paths:
    - "**.ts"
exclude_paths:
  - lib
  - test